import type { Metadata } from "next";
// Configura a fonte geral
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Paviotti's Home Page",
  description: "Generated by By Vercel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <h2>Hola de nuevo! (Layout)</h2>
        {children}
      </body>
    </html>
  );
}
